version: "3"
services:
    php-app:
        build:
            context: ../../
            dockerfile: deploy/docker/Dockerfile
        image: laravel/laravel-api
        container_name: laravel-php-app
        restart: always
        networks:
            - laravel-api-net
        volumes:
            - ../../:/var/www/html

    nginx:
        build:
            context: ../../
            dockerfile: deploy/docker/nginx/Dockerfile
        image: laravel/laravel-nginx
        container_name: laravel-nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ../../:/var/www/html
        networks:
            - laravel-api-net
        restart: always

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=12345
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - laravel-api-net
        restart: always

volumes:
    mysql_data:
        driver: local

networks:
    laravel-api-net: